using System.Collections.Generic;

namespace BarcodeLib.Symbologies.EAN13Encoder
{
	public static class CountryCodes
    {
        private static Dictionary<int, string> _countryCodes;

        public static Dictionary<int, string> CountryCodesDictionary
        {
            get
            {
                if (_countryCodes == null)
                {
                    _countryCodes = new Dictionary<int, string>()
                    {
                        { 000, "US / CANADA" },
                        { 001, "US / CANADA" },
                        { 002, "US / CANADA" },
                        { 003, "US / CANADA" },
                        { 004, "US / CANADA" },
                        { 005, "US / CANADA" },
                        { 006, "US / CANADA" },
                        { 007, "US / CANADA" },
                        { 008, "US / CANADA" },
                        { 009, "US / CANADA" },
                        { 010, "US / CANADA" },
                        { 011, "US / CANADA" },
                        { 012, "US / CANADA" },
                        { 013, "US / CANADA" },
                        { 020, "IN STORE" },
                        { 021, "IN STORE" },
                        { 022, "IN STORE" },
                        { 023, "IN STORE" },
                        { 024, "IN STORE" },
                        { 025, "IN STORE" },
                        { 026, "IN STORE" },
                        { 027, "IN STORE" },
                        { 028, "IN STORE" },
                        { 029, "IN STORE" },
                        { 030, "FRANCE" },
                        { 031, "FRANCE" },
                        { 032, "FRANCE" },
                        { 033, "FRANCE" },
                        { 034, "FRANCE" },
                        { 035, "FRANCE" },
                        { 036, "FRANCE" },
                        { 037, "FRANCE" },
                        { 040, "GERMANY" },
                        { 041, "GERMANY" },
                        { 042, "GERMANY" },
                        { 043, "GERMANY" },
                        { 044, "GERMANY" },
                        { 045, "JAPAN" },
                        { 046, "RUSSIAN FEDERATION" },
                        { 049, "JAPAN (JAN-13)" },
                        { 050, "UNITED KINGDOM" },
                        { 054, "BELGIUM / LUXEMBOURG" },
                        { 057, "DENMARK" },
                        { 064, "FINLAND" },
                        { 070, "NORWAY" },
                        { 073, "SWEDEN" },
                        { 076, "SWITZERLAND" },
                        { 080, "ITALY" },
                        { 081, "ITALY" },
                        { 082, "ITALY" },
                        { 083, "ITALY" },
                        { 084, "SPAIN" },
                        { 087, "NETHERLANDS" },
                        { 090, "AUSTRIA" },
                        { 091, "AUSTRIA" },
                        { 093, "AUSTRALIA" },
                        { 094, "NEW ZEALAND" },
                        { 099, "COUPONS" },
                        { 100, "UNITED STATES" },
                        { 101, "UNITED STATES" },
                        { 102, "UNITED STATES" },
                        { 103, "UNITED STATES" },
                        { 104, "UNITED STATES" },
                        { 105, "UNITED STATES" },
                        { 106, "UNITED STATES" },
                        { 107, "UNITED STATES" },
                        { 108, "UNITED STATES" },
                        { 109, "UNITED STATES" },
                        { 110, "UNITED STATES" },
                        { 111, "UNITED STATES" },
                        { 112, "UNITED STATES" },
                        { 113, "UNITED STATES" },
                        { 114, "UNITED STATES" },
                        { 115, "UNITED STATES" },
                        { 116, "UNITED STATES" },
                        { 117, "UNITED STATES" },
                        { 118, "UNITED STATES" },
                        { 119, "UNITED STATES" },
                        { 120, "UNITED STATES" },
                        { 121, "UNITED STATES" },
                        { 122, "UNITED STATES" },
                        { 123, "UNITED STATES" },
                        { 124, "UNITED STATES" },
                        { 125, "UNITED STATES" },
                        { 126, "UNITED STATES" },
                        { 127, "UNITED STATES" },
                        { 128, "UNITED STATES" },
                        { 129, "UNITED STATES" },
                        { 130, "UNITED STATES" },
                        { 131, "UNITED STATES" },
                        { 132, "UNITED STATES" },
                        { 133, "UNITED STATES" },
                        { 134, "UNITED STATES" },
                        { 135, "UNITED STATES" },
                        { 136, "UNITED STATES" },
                        { 137, "UNITED STATES" },
                        { 138, "UNITED STATES" },
                        { 139, "UNITED STATES" },
                        { 300, "FRANCE AND MONACO" },
                        { 301, "FRANCE AND MONACO" },
                        { 302, "FRANCE AND MONACO" },
                        { 303, "FRANCE AND MONACO" },
                        { 304, "FRANCE AND MONACO" },
                        { 305, "FRANCE AND MONACO" },
                        { 306, "FRANCE AND MONACO" },
                        { 307, "FRANCE AND MONACO" },
                        { 308, "FRANCE AND MONACO" },
                        { 309, "FRANCE AND MONACO" },
                        { 310, "FRANCE AND MONACO" },
                        { 311, "FRANCE AND MONACO" },
                        { 312, "FRANCE AND MONACO" },
                        { 313, "FRANCE AND MONACO" },
                        { 314, "FRANCE AND MONACO" },
                        { 315, "FRANCE AND MONACO" },
                        { 316, "FRANCE AND MONACO" },
                        { 317, "FRANCE AND MONACO" },
                        { 318, "FRANCE AND MONACO" },
                        { 319, "FRANCE AND MONACO" },
                        { 320, "FRANCE AND MONACO" },
                        { 321, "FRANCE AND MONACO" },
                        { 322, "FRANCE AND MONACO" },
                        { 323, "FRANCE AND MONACO" },
                        { 324, "FRANCE AND MONACO" },
                        { 325, "FRANCE AND MONACO" },
                        { 326, "FRANCE AND MONACO" },
                        { 327, "FRANCE AND MONACO" },
                        { 328, "FRANCE AND MONACO" },
                        { 329, "FRANCE AND MONACO" },
                        { 330, "FRANCE AND MONACO" },
                        { 331, "FRANCE AND MONACO" },
                        { 332, "FRANCE AND MONACO" },
                        { 333, "FRANCE AND MONACO" },
                        { 334, "FRANCE AND MONACO" },
                        { 335, "FRANCE AND MONACO" },
                        { 336, "FRANCE AND MONACO" },
                        { 337, "FRANCE AND MONACO" },
                        { 338, "FRANCE AND MONACO" },
                        { 339, "FRANCE AND MONACO" },
                        { 340, "FRANCE AND MONACO" },
                        { 341, "FRANCE AND MONACO" },
                        { 342, "FRANCE AND MONACO" },
                        { 343, "FRANCE AND MONACO" },
                        { 344, "FRANCE AND MONACO" },
                        { 345, "FRANCE AND MONACO" },
                        { 346, "FRANCE AND MONACO" },
                        { 347, "FRANCE AND MONACO" },
                        { 348, "FRANCE AND MONACO" },
                        { 349, "FRANCE AND MONACO" },
                        { 350, "FRANCE AND MONACO" },
                        { 351, "FRANCE AND MONACO" },
                        { 352, "FRANCE AND MONACO" },
                        { 353, "FRANCE AND MONACO" },
                        { 354, "FRANCE AND MONACO" },
                        { 355, "FRANCE AND MONACO" },
                        { 356, "FRANCE AND MONACO" },
                        { 357, "FRANCE AND MONACO" },
                        { 358, "FRANCE AND MONACO" },
                        { 359, "FRANCE AND MONACO" },
                        { 360, "FRANCE AND MONACO" },
                        { 361, "FRANCE AND MONACO" },
                        { 362, "FRANCE AND MONACO" },
                        { 363, "FRANCE AND MONACO" },
                        { 364, "FRANCE AND MONACO" },
                        { 365, "FRANCE AND MONACO" },
                        { 366, "FRANCE AND MONACO" },
                        { 367, "FRANCE AND MONACO" },
                        { 368, "FRANCE AND MONACO" },
                        { 369, "FRANCE AND MONACO" },
                        { 370, "FRANCE AND MONACO" },
                        { 371, "FRANCE AND MONACO" },
                        { 372, "FRANCE AND MONACO" },
                        { 373, "FRANCE AND MONACO" },
                        { 374, "FRANCE AND MONACO" },
                        { 375, "FRANCE AND MONACO" },
                        { 376, "FRANCE AND MONACO" },
                        { 377, "FRANCE AND MONACO" },
                        { 378, "FRANCE AND MONACO" },
                        { 379, "FRANCE AND MONACO" },
                        { 380, "BULGARIA" },
                        { 383, "SLOVENIJA" },
                        { 385, "CROATIA" },
                        { 387, "BOSNIA-HERZEGOVINA" },
                        { 389, "MONTENEGRO" },
                        { 400, "GERMANY" },
                        { 401, "GERMANY" },
                        { 402, "GERMANY" },
                        { 403, "GERMANY" },
                        { 404, "GERMANY" },
                        { 405, "GERMANY" },
                        { 406, "GERMANY" },
                        { 407, "GERMANY" },
                        { 408, "GERMANY" },
                        { 409, "GERMANY" },
                        { 410, "GERMANY" },
                        { 411, "GERMANY" },
                        { 412, "GERMANY" },
                        { 413, "GERMANY" },
                        { 414, "GERMANY" },
                        { 415, "GERMANY" },
                        { 416, "GERMANY" },
                        { 417, "GERMANY" },
                        { 418, "GERMANY" },
                        { 419, "GERMANY" },
                        { 420, "GERMANY" },
                        { 421, "GERMANY" },
                        { 422, "GERMANY" },
                        { 423, "GERMANY" },
                        { 424, "GERMANY" },
                        { 425, "GERMANY" },
                        { 426, "GERMANY" },
                        { 427, "GERMANY" },
                        { 428, "GERMANY" },
                        { 429, "GERMANY" },
                        { 430, "GERMANY" },
                        { 431, "GERMANY" },
                        { 432, "GERMANY" },
                        { 433, "GERMANY" },
                        { 434, "GERMANY" },
                        { 435, "GERMANY" },
                        { 436, "GERMANY" },
                        { 437, "GERMANY" },
                        { 438, "GERMANY" },
                        { 439, "GERMANY" },
                        { 440, "GERMANY" },
                        { 450, "JAPAN" },
                        { 451, "JAPAN" },
                        { 452, "JAPAN" },
                        { 453, "JAPAN" },
                        { 454, "JAPAN" },
                        { 455, "JAPAN" },
                        { 456, "JAPAN" },
                        { 457, "JAPAN" },
                        { 458, "JAPAN" },
                        { 459, "JAPAN" },
                        { 460, "RUSSIA" },
                        { 461, "RUSSIA" },
                        { 462, "RUSSIA" },
                        { 463, "RUSSIA" },
                        { 464, "RUSSIA" },
                        { 465, "RUSSIA" },
                        { 466, "RUSSIA" },
                        { 467, "RUSSIA" },
                        { 468, "RUSSIA" },
                        { 469, "RUSSIA" },
                        { 470, "KYRGYZSTAN" },
                        { 471, "TAIWAN" },
                        { 474, "ESTONIA" },
                        { 475, "LATVIA" },
                        { 476, "AZERBAIJAN" },
                        { 477, "LITHUANIA" },
                        { 478, "UZBEKISTAN" },
                        { 479, "SRI LANKA" },
                        { 480, "PHILIPPINES" },
                        { 481, "BELARUS" },
                        { 482, "UKRAINE" },
                        { 483, "TURKMENISTAN" },
                        { 484, "MOLDOVA" },
                        { 485, "ARMENIA" },
                        { 486, "GEORGIA" },
                        { 487, "KAZAKHSTAN" },
                        { 488, "TAJIKISTAN" },
                        { 489, "HONG KONG" },
                        { 490, "JAPAN" },
                        { 491, "JAPAN" },
                        { 492, "JAPAN" },
                        { 493, "JAPAN" },
                        { 494, "JAPAN" },
                        { 495, "JAPAN" },
                        { 496, "JAPAN" },
                        { 497, "JAPAN" },
                        { 498, "JAPAN" },
                        { 499, "JAPAN" },
                        { 500, "UNITED KINGDOM" },
                        { 501, "UNITED KINGDOM" },
                        { 502, "UNITED KINGDOM" },
                        { 503, "UNITED KINGDOM" },
                        { 504, "UNITED KINGDOM" },
                        { 505, "UNITED KINGDOM" },
                        { 506, "UNITED KINGDOM" },
                        { 507, "UNITED KINGDOM" },
                        { 508, "UNITED KINGDOM" },
                        { 509, "UNITED KINGDOM" },
                        { 520, "GREECE" },
                        { 521, "GREECE" },
                        { 528, "LEBANON" },
                        { 529, "CYPRUS" },
                        { 530, "ALBANIA" },
                        { 531, "MACEDONIA" },
                        { 535, "MALTA" },
                        { 539, "IRELAND" },
                        { 540, "BELGIUM AND LUXEMBOURG" },
                        { 541, "BELGIUM AND LUXEMBOURG" },
                        { 542, "BELGIUM AND LUXEMBOURG" },
                        { 543, "BELGIUM AND LUXEMBOURG" },
                        { 544, "BELGIUM AND LUXEMBOURG" },
                        { 545, "BELGIUM AND LUXEMBOURG" },
                        { 546, "BELGIUM AND LUXEMBOURG" },
                        { 547, "BELGIUM AND LUXEMBOURG" },
                        { 548, "BELGIUM AND LUXEMBOURG" },
                        { 549, "BELGIUM AND LUXEMBOURG" },
                        { 560, "PORTUGAL" },
                        { 569, "ICELAND" },
                        { 570, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 571, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 572, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 573, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 574, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 575, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 576, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 577, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 578, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 579, "DENMARK, FAROE ISLANDS AND GREENLAND" },
                        { 590, "POLAND" },
                        { 594, "ROMANIA" },
                        { 599, "HUNGARY" },
                        { 600, "SOUTH AFRICA" },
                        { 601, "SOUTH AFRICA" },
                        { 603, "GHANA" },
                        { 604, "SENEGAL" },
                        { 608, "BAHRAIN" },
                        { 609, "MAURITIUS" },
                        { 611, "MOROCCO" },
                        { 613, "ALGERIA" },
                        { 615, "NIGERIA" },
                        { 616, "KENYA" },
                        { 618, "IVORY COAST" },
                        { 619, "TUNISIA" },
                        { 620, "TANZANIA" },
                        { 621, "SYRIA" },
                        { 622, "EGYPT" },
                        { 623, "BRUNEI" },
                        { 624, "LIBYA" },
                        { 625, "JORDAN" },
                        { 626, "IRAN" },
                        { 627, "KUWAIT" },
                        { 628, "SAUDI ARABIA" },
                        { 629, "EMIRATES" },
                        { 640, "FINLAND" },
                        { 641, "FINLAND" },
                        { 642, "FINLAND" },
                        { 643, "FINLAND" },
                        { 644, "FINLAND" },
                        { 645, "FINLAND" },
                        { 646, "FINLAND" },
                        { 647, "FINLAND" },
                        { 648, "FINLAND" },
                        { 649, "FINLAND" },
                        { 690, "CHINA" },
                        { 691, "CHINA" },
                        { 692, "CHINA" },
                        { 693, "CHINA" },
                        { 694, "CHINA" },
                        { 695, "CHINA" },
                        { 696, "CHINA" },
                        { 697, "CHINA" },
                        { 698, "CHINA" },
                        { 699, "CHINA" },
                        { 700, "NORWAY" },
                        { 701, "NORWAY" },
                        { 702, "NORWAY" },
                        { 703, "NORWAY" },
                        { 704, "NORWAY" },
                        { 705, "NORWAY" },
                        { 706, "NORWAY" },
                        { 707, "NORWAY" },
                        { 708, "NORWAY" },
                        { 709, "NORWAY" },
                        { 729, "ISRAEL" },
                        { 730, "SWEDEN" },
                        { 731, "SWEDEN" },
                        { 732, "SWEDEN" },
                        { 733, "SWEDEN" },
                        { 734, "SWEDEN" },
                        { 735, "SWEDEN" },
                        { 736, "SWEDEN" },
                        { 737, "SWEDEN" },
                        { 738, "SWEDEN" },
                        { 739, "SWEDEN" },
                        { 740, "GUATEMALA" },
                        { 741, "EL SALVADOR" },
                        { 742, "HONDURAS" },
                        { 743, "NICARAGUA" },
                        { 744, "COSTA RICA" },
                        { 745, "PANAMA" },
                        { 746, "DOMINICAN REPUBLIC" },
                        { 750, "MEXICO" },
                        { 754, "CANADA" },
                        { 755, "CANADA" },
                        { 759, "VENEZUELA" },
                        { 760, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 761, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 762, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 763, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 764, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 765, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 766, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 767, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 768, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 769, "SWITZERLAND AND LIECHTENSTEIN" },
                        { 770, "COLOMBIA" },
                        { 773, "URUGUAY" },
                        { 775, "PERU" },
                        { 777, "BOLIVIA" },
                        { 778, "ARGENTINA" },
                        { 779, "ARGENTINA" },
                        { 780, "CHILE" },
                        { 784, "PARAGUAY" },
                        { 785, "PERU" },
                        { 786, "ECUADOR" },
                        { 789, "BRAZIL" },
                        { 790, "BRAZIL" },
                        { 800, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 801, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 802, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 803, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 804, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 805, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 806, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 807, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 808, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 809, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 810, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 811, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 812, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 813, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 814, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 815, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 816, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 817, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 818, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 819, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 820, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 821, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 822, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 823, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 824, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 825, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 826, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 827, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 828, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 829, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 830, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 831, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 832, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 833, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 834, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 835, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 836, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 837, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 838, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 839, "ITALY, SAN MARINO AND VATICAN CITY" },
                        { 840, "SPAIN AND ANDORRA" },
                        { 841, "SPAIN AND ANDORRA" },
                        { 842, "SPAIN AND ANDORRA" },
                        { 843, "SPAIN AND ANDORRA" },
                        { 844, "SPAIN AND ANDORRA" },
                        { 845, "SPAIN AND ANDORRA" },
                        { 846, "SPAIN AND ANDORRA" },
                        { 847, "SPAIN AND ANDORRA" },
                        { 848, "SPAIN AND ANDORRA" },
                        { 849, "SPAIN AND ANDORRA" },
                        { 850, "CUBA" },
                        { 858, "SLOVAKIA" },
                        { 859, "CZECH REPUBLIC" },
                        { 860, "SERBIA" },
                        { 865, "MONGOLIA" },
                        { 867, "NORTH KOREA" },
                        { 868, "TURKEY" },
                        { 869, "TURKEY" },
                        { 870, "NETHERLANDS" },
                        { 871, "NETHERLANDS" },
                        { 872, "NETHERLANDS" },
                        { 873, "NETHERLANDS" },
                        { 874, "NETHERLANDS" },
                        { 875, "NETHERLANDS" },
                        { 876, "NETHERLANDS" },
                        { 877, "NETHERLANDS" },
                        { 878, "NETHERLANDS" },
                        { 879, "NETHERLANDS" },
                        { 880, "SOUTH KOREA" },
                        { 884, "CAMBODIA" },
                        { 885, "THAILAND" },
                        { 888, "SINGAPORE" },
                        { 890, "INDIA" },
                        { 893, "VIETNAM" },
                        { 896, "PAKISTAN" },
                        { 899, "INDONESIA" },
                        { 900, "AUSTRIA" },
                        { 901, "AUSTRIA" },
                        { 902, "AUSTRIA" },
                        { 903, "AUSTRIA" },
                        { 904, "AUSTRIA" },
                        { 905, "AUSTRIA" },
                        { 906, "AUSTRIA" },
                        { 907, "AUSTRIA" },
                        { 908, "AUSTRIA" },
                        { 909, "AUSTRIA" },
                        { 930, "AUSTRALIA" },
                        { 931, "AUSTRALIA" },
                        { 932, "AUSTRALIA" },
                        { 933, "AUSTRALIA" },
                        { 934, "AUSTRALIA" },
                        { 935, "AUSTRALIA" },
                        { 936, "AUSTRALIA" },
                        { 937, "AUSTRALIA" },
                        { 938, "AUSTRALIA" },
                        { 939, "AUSTRALIA" },
                        { 940, "NEW ZEALAND" },
                        { 941, "NEW ZEALAND" },
                        { 942, "NEW ZEALAND" },
                        { 943, "NEW ZEALAND" },
                        { 944, "NEW ZEALAND" },
                        { 945, "NEW ZEALAND" },
                        { 946, "NEW ZEALAND" },
                        { 947, "NEW ZEALAND" },
                        { 948, "NEW ZEALAND" },
                        { 949, "NEW ZEALAND" },
                        { 950, "GS1 GLOBAL OFFICE SPECIAL APPLICATIONS" },
                        { 951, "EPC GLOBAL SPECIAL APPLICATIONS" },
                        { 955, "MALAYSIA" },
                        { 958, "MACAU" },
                        { 960, "GS1 UK: GTIN-8 ALLOCATIONS" },
                        { 961, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 962, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 963, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 964, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 965, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 966, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 967, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 968, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 969, "GS1 GLOBAL OFFICE: GTIN-8 ALLOCATIONS" },
                        { 977, "INTERNATIONAL STANDARD SERIAL NUMBER FOR PERIODICALS (ISSN)" },
                        { 978, "INTERNATIONAL STANDARD BOOK NUMBERING (ISBN)" },
                        { 979, "INTERNATIONAL STANDARD MUSIC NUMBER (ISMN)" },
                        { 980, "REFUND RECEIPTS" },
                        { 981, "COMMON CURRENCY COUPONS" },
                        { 982, "COMMON CURRENCY COUPONS" },
                        { 983, "COMMON CURRENCY COUPONS" },
                        { 984, "COMMON CURRENCY COUPONS" },
                        { 990, "COUPONS" },
                        { 991, "COUPONS" },
                        { 992, "COUPONS" },
                        { 993, "COUPONS" },
                        { 994, "COUPONS" },
                        { 995, "COUPONS" },
                        { 996, "COUPONS" },
                        { 997, "COUPONS" },
                        { 998, "COUPONS" },
                        { 999, "COUPONS" }
                    };
                }

                return _countryCodes;
            }
        }
    }
}
